"""Composable analysis of ordinary SymPy expressions."""

from .analysis import (
    BoundResult,
    ContributionBound,
    DefinednessResult,
    ExpressionAnalyzer,
    ProofVerdict,
    Sign,
    SignProof,
    SignRequirement,
    SignResult,
    SumProof,
    ZeroProof,
)
from .evaluation import (
    CSEStats,
    EvaluationProfile,
    ExpressionStats,
    OPERATION_ORDER,
    SharedTerm,
    profile_evaluation,
)
from .differential import (
    BranchReduction,
    DerivativeBound,
    DifferentialSolverProfile,
    DomainDifferentialProfile,
    FeedbackKind,
    MatrixEnvelope,
    RateDifferentialProfile,
    Regularity,
    SurfaceLocation,
    SurfaceProfile,
    profile_differential,
    reduce_branches,
    symbolic_derivative,
)
from .lipschitz import (
    GradientEnvelope,
    GuardMargin,
    LipschitzCertificate,
    LipschitzResult,
    NetworkLipschitzCertificate,
    derive_network_lipschitz,
)

__all__ = (
    "BoundResult",
    "BranchReduction",
    "ContributionBound",
    "CSEStats",
    "DefinednessResult",
    "DerivativeBound",
    "DifferentialSolverProfile",
    "DomainDifferentialProfile",
    "EvaluationProfile",
    "ExpressionAnalyzer",
    "ExpressionStats",
    "FeedbackKind",
    "GradientEnvelope",
    "GuardMargin",
    "LipschitzCertificate",
    "LipschitzResult",
    "MatrixEnvelope",
    "NetworkLipschitzCertificate",
    "OPERATION_ORDER",
    "ProofVerdict",
    "RateDifferentialProfile",
    "Regularity",
    "Sign",
    "SignProof",
    "SignRequirement",
    "SignResult",
    "SumProof",
    "SharedTerm",
    "SurfaceLocation",
    "SurfaceProfile",
    "ZeroProof",
    "derive_network_lipschitz",
    "profile_evaluation",
    "profile_differential",
    "reduce_branches",
    "symbolic_derivative",
)
