"""Public API for rxn-checker."""

from .case import (
    Case,
    CheckConfig,
    ConcentrationModel,
    DomainConfig,
    ParameterBox,
    ParameterRange,
    ReportConfig,
    TotalMinimumConfig,
    TotalMinimumMode,
)
from .checks import (
    CHECK_REGISTRY,
    AtomConservationResult,
    CheckContext,
    CheckDefinition,
    CheckOutcome,
    CheckScope,
    CheckStatus,
    CheckValue,
    ConservationComponent,
    ConservedQuantity,
    EquilibriumBranch,
    EquilibriumHelper,
    EquilibriumRelation,
    LipschitzContinuityResult,
    MassConservationResult,
    NegativeSideRecoveryResult,
    NegativeSideSpeciesResult,
    StoichiometricConservationResult,
    TerminalFaceSearchResult,
    check_atom_conservation,
    check_equilibria,
    check_lipschitz_continuity,
    check_mass_conservation,
    check_negative_side_recovery,
    check_terminal_faces,
    find_conserved_quantities,
    run_checks,
)
from .loading import load_case
from .model import CaseSymbols, Phase, Reaction, Species, parse_rational
from .reporting import CheckReport, build_check_report
from .state import IdealGasClosure, StateVariables, VariableBounds

__all__ = (
    "CHECK_REGISTRY",
    "AtomConservationResult",
    "Case",
    "CaseSymbols",
    "CheckConfig",
    "CheckContext",
    "CheckDefinition",
    "CheckOutcome",
    "CheckReport",
    "CheckScope",
    "CheckStatus",
    "CheckValue",
    "ConservationComponent",
    "ConcentrationModel",
    "ConservedQuantity",
    "DomainConfig",
    "EquilibriumBranch",
    "EquilibriumHelper",
    "EquilibriumRelation",
    "IdealGasClosure",
    "LipschitzContinuityResult",
    "MassConservationResult",
    "NegativeSideRecoveryResult",
    "NegativeSideSpeciesResult",
    "ParameterBox",
    "ParameterRange",
    "Phase",
    "Reaction",
    "ReportConfig",
    "Species",
    "StateVariables",
    "StoichiometricConservationResult",
    "TerminalFaceSearchResult",
    "TotalMinimumConfig",
    "TotalMinimumMode",
    "VariableBounds",
    "build_check_report",
    "check_atom_conservation",
    "check_equilibria",
    "check_lipschitz_continuity",
    "check_mass_conservation",
    "check_negative_side_recovery",
    "check_terminal_faces",
    "find_conserved_quantities",
    "load_case",
    "parse_rational",
    "run_checks",
)
