"""Public API for rxn-checker."""

from .case import Case
from .checks import (
    CHECK_REGISTRY,
    AtomConservationResult,
    CheckContext,
    CheckDefinition,
    CheckOutcome,
    CheckScope,
    CheckStatus,
    CheckValue,
    ConservationComponent,
    ConservedQuantity,
    EquilibriumBranch,
    EquilibriumHelper,
    EquilibriumRelation,
    MassConservationResult,
    NonphysicalRecoveryResult,
    RecoveryRegionResult,
    RecoveryVerdict,
    StoichiometricConservationResult,
    TerminalFaceSearchResult,
    check_atom_conservation,
    check_equilibria,
    check_mass_conservation,
    check_nonphysical_recovery,
    check_terminal_faces,
    find_conserved_quantities,
    run_checks,
)
from .loading import load_case
from .reaction import Reaction
from .reporting import CheckReport, build_check_report
from .state import StateVariables, VariableBounds

__all__ = (
    "CHECK_REGISTRY",
    "AtomConservationResult",
    "Case",
    "CheckContext",
    "CheckDefinition",
    "CheckOutcome",
    "CheckReport",
    "CheckScope",
    "CheckStatus",
    "CheckValue",
    "ConservationComponent",
    "ConservedQuantity",
    "EquilibriumBranch",
    "EquilibriumHelper",
    "EquilibriumRelation",
    "MassConservationResult",
    "NonphysicalRecoveryResult",
    "Reaction",
    "RecoveryRegionResult",
    "RecoveryVerdict",
    "StateVariables",
    "StoichiometricConservationResult",
    "TerminalFaceSearchResult",
    "VariableBounds",
    "build_check_report",
    "check_atom_conservation",
    "check_equilibria",
    "check_mass_conservation",
    "check_nonphysical_recovery",
    "check_terminal_faces",
    "find_conserved_quantities",
    "load_case",
    "run_checks",
)
